apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-demo-ingress
  namespace: 13th
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo.local  # Thay đổi domain của bạn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-demo-service
            port:
              number: 80