apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-service
  namespace: default
spec:
  type: LoadBalancer  # Hoặc NodePort cho local
  selector:
    app: argocd-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30080  # Uncomment nếu dùng NodePort